import { Resend } from 'resend'
import { formatDistanceToNow } from 'date-fns'
import { es } from 'date-fns/locale'
import { createClient } from '@/lib/supabase/server'

export type AdminNotificationSeverity = 'info' | 'success' | 'warning' | 'critical'

export type AdminNotification = {
  id: string
  title: string
  message: string
  severity: AdminNotificationSeverity
  createdAt: string
  relativeTime: string
  href?: string
  source: 'database' | 'derived'
}

export type NotificationRule = {
  id: string
  title: string
  description: string
  channel: 'panel' | 'email' | 'panel+email'
}

const ADMIN_EMAIL = 'carlos.cervart@icloud.com'

export const NOTIFICATION_RULES: NotificationRule[] = [
  {
    id: 'new-contact',
    title: 'New contact message',
    description: 'Every new contact message should be visible in the panel and sent via email.',
    channel: 'panel+email',
  },
  {
    id: 'new-diagnostic-lead',
    title: 'New diagnostic lead',
    description: 'Every lead generated by the QA diagnostic should be shown in the panel and sent via email.',
    channel: 'panel+email',
  },
  {
    id: 'draft-reminder',
    title: 'Pending drafts',
    description: 'If there are draft posts, the panel should remind to avoid forgotten content.',
    channel: 'panel',
  },
  {
    id: 'analytics-status',
    title: 'Analytics status',
    description: 'If Vercel Analytics is not configured or fails, the panel should alert about it.',
    channel: 'panel',
  },
]

function getResendClient() {
  if (!process.env.RESEND_API_KEY) return null
  return new Resend(process.env.RESEND_API_KEY)
}

function withRelativeTime<T extends { createdAt: string }>(items: T[]) {
  return items.map((item) => ({
    ...item,
    relativeTime: formatDistanceToNow(new Date(item.createdAt), {
      addSuffix: true,
      locale: es,
    }),
  }))
}

export async function createAdminNotification(input: {
  title: string
  message: string
  severity?: AdminNotificationSeverity
  href?: string
}) {
  const supabase = await createClient()
  if (!supabase) return false

  const { error } = await supabase.from('admin_notifications').insert({
    title: input.title,
    message: input.message,
    severity: input.severity ?? 'info',
    href: input.href ?? null,
  })

  return !error
}

export async function sendAdminNotificationEmail(input: {
  subject: string
  title: string
  message: string
  htmlDetails?: string
}) {
  const resend = getResendClient()
  if (!resend) return false

  await resend.emails.send({
    from: 'Admin Notifications <hello@carloscervantes.com>',
    to: ADMIN_EMAIL,
    subject: input.subject,
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'SF Pro Text','Helvetica Neue',Arial,sans-serif;max-width:640px;margin:0 auto;color:#1d1d1f;">
        <div style="padding:24px 0 8px;">
          <div style="display:inline-block;padding:8px 12px;border:1px solid #d2d2d7;border-radius:999px;background:#f5f5f7;font-size:11px;font-weight:600;letter-spacing:0.12em;text-transform:uppercase;color:#86868b;">
            Admin Notification
          </div>
        </div>
        <h1 style="font-size:28px;line-height:1.1;letter-spacing:-0.03em;margin:8px 0 12px;">${input.title}</h1>
        <p style="font-size:16px;line-height:1.6;color:#4b5563;margin:0 0 20px;">${input.message}</p>
        ${input.htmlDetails ?? ''}
        <hr style="border:none;border-top:1px solid #e5e7eb;margin:32px 0;" />
        <p style="font-size:12px;color:#86868b;">Carlos Cervantes · Admin Panel Notification</p>
      </div>
    `,
  })

  return true
}

async function fetchStoredNotifications() {
  const supabase = await createClient()
  if (!supabase) return []

  const { data, error } = await supabase
    .from('admin_notifications')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(8)

  if (error || !data) return []

  return withRelativeTime(
    data.map((item: any) => ({
      id: String(item.id),
      title: String(item.title),
      message: String(item.message),
      severity: (item.severity as AdminNotificationSeverity) ?? 'info',
      createdAt: item.created_at ?? new Date().toISOString(),
      href: item.href ?? undefined,
      source: 'database' as const,
    }))
  )
}

export async function getAdminNotifications(): Promise<AdminNotification[]> {
  const stored = await fetchStoredNotifications()
  if (stored.length > 0) return stored

  const supabase = await createClient()
  const derived: Array<Omit<AdminNotification, 'relativeTime'>> = []

  if (!supabase) {
    return withRelativeTime([
      {
        id: 'supabase-missing',
        title: 'Supabase not configured',
        message: 'The panel cannot read leads or dynamic content because Supabase environment variables are missing.',
        severity: 'warning',
        createdAt: new Date().toISOString(),
        href: '/admin',
        source: 'derived',
      },
    ])
  }

  const [{ data: leads }, { data: drafts }, { data: contactMessages }, { data: profile }] = await Promise.all([
    supabase
      .from('diagnostico_leads')
      .select('id,nombre,empresa,created_at,paquete_recomendado,score')
      .order('created_at', { ascending: false })
      .limit(3),
    supabase
      .from('blog_posts')
      .select('id,titulo,estado,updated_at')
      .eq('estado', 'borrador')
      .order('updated_at', { ascending: false })
      .limit(3),
    supabase
      .from('contact_messages')
      .select('id,nombre,servicio,created_at')
      .order('created_at', { ascending: false })
      .limit(3),
    supabase
      .from('site_profile')
      .select('updated_at,nombre,titulo')
      .single(),
  ])

  ;(leads ?? []).forEach((lead: any) => {
    derived.push({
      id: `lead-${lead.id}`,
      title: `New lead: ${lead.nombre}`,
      message: `${lead.empresa || 'Project without company'} · ${lead.paquete_recomendado || 'Package TBD'} · score ${lead.score ?? 'N/A'}`,
      severity: 'success',
      createdAt: lead.created_at ?? new Date().toISOString(),
      href: '/admin',
      source: 'derived',
    })
  })

  ;(contactMessages ?? []).forEach((message: any) => {
    derived.push({
      id: `contact-${message.id}`,
      title: `New message: ${message.nombre}`,
      message: `Interested in ${message.servicio || 'general consulting'}. Review and reply from your email.`,
      severity: 'info',
      createdAt: message.created_at ?? new Date().toISOString(),
      href: '/admin',
      source: 'derived',
    })
  })

  const draftItems = drafts ?? []

  if (draftItems.length > 0) {
    derived.push({
      id: 'drafts-pending',
      title: `${draftItems.length} pending draft(s)`,
      message: 'There is unpublished blog content. You should review it to keep the blog active.',
      severity: 'warning',
      createdAt: draftItems[0]?.updated_at ?? new Date().toISOString(),
      href: '/admin/blog',
      source: 'derived',
    })
  }

  if (!process.env.VERCEL_API_TOKEN || !process.env.VERCEL_PROJECT_ID) {
    derived.push({
      id: 'analytics-missing',
      title: 'Web analytics not configured',
      message: 'Missing VERCEL_API_TOKEN or VERCEL_PROJECT_ID. Dashboard will only show real internal metrics.',
      severity: 'warning',
      createdAt: new Date().toISOString(),
      href: '/admin',
      source: 'derived',
    })
  }

  if (!profile?.updated_at) {
    derived.push({
      id: 'profile-review',
      title: 'Professional profile to review',
      message: 'No recent update of the public profile was found. Verify that the main information is complete.',
      severity: 'warning',
      createdAt: new Date().toISOString(),
      href: '/admin/perfil',
      source: 'derived',
    })
  }

  return withRelativeTime(
    derived
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
      .slice(0, 8)
  )
}
