name: Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check for syntax errors
      run: node -c app.js
    
    - name: Setup MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '6.0'
    
    - name: Create .env file for testing
      run: |
        echo "NODE_ENV=test" > .env
        echo "MONGODB_URI=mongodb://localhost:27017/personal-portfolio-test" >> .env
        echo "PORT=3000" >> .env
    
    - name: Test if server starts
      run: |
        timeout 10s node app.js || code=$?
        if [[ $code -ne 124 && $code -ne 0 ]]; then
          echo "Server failed to start"
          exit 1
        fi
        echo "Server started successfully"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Trigger Render Deploy
      run: |
        if [ -n "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
          echo "Deployment triggered on Render"
        else
          echo "No Render deploy hook configured - Render will auto-deploy from GitHub"
        fi
